name = "Pan Xiao"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Student, Network and Linux Nerd, And music staff"
#company = ""
location = "China"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
