[[main]]
  identifier = "dropdown"
  name = "更多"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "github"
  parent = "dropdown"
  name = "Github"
  weight = 5
  url = "https://github.com/panxiao81/new-blog"
[[main]]
  id = "debian"
  parent = "dropdown"
  name = "Debian 快速入门指南"
  weight = 1
  url = "https://blog.ddupan.top/Chinaskills-Debian"
[[main]]
  id = "git"
  parent = "dropdown"
  name = "Gitea"
  weight = 4
  url = "https://git.apps.ddupan.top/panxiao81/"
[[main]]
  id = "tlpi"
  parent = "dropdown"
  name = "TLPI 笔记"
  weight = 2
  url = "https://blog.ddupan.top/learn-tlpi"
[[main]]
  id = "csapp"
  parent = "dropdown"
  name = " CS:APP 笔记"
  weight = 3
  url = "https://blog.ddupan.top/learn-csapp"