# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "Pan Xiao's Blog, Write Down Tech and My Life"
keywords = "Linux, Network, IT"
# images = ["site-feature-image.jpg"]

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
brand = "Pan Xiao's Blog"
# menusPosition = "left" # Menus position: right(default), left or center.

palette = "blue" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

# color = "dark" # light, dark or dynamic. Default to dynamic.

# fullWidth = true # Full width.
# fixedHeader = false # Turn on/off fixed header.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = "ca-pub-4922564642438130"

math = true # Enable math globally.
# toc = true # Disable TOC globally.
diagram = true
# breadcrumb = false # Disable breadcrumb

# poweredBy = false # Whether to show powered by.

# featuredPostCount = 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount = 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount = 10 # The number of related posts. Turn off by setting it to false.
# categoryCount = 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount = 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount = 10 # The number of series shown in sidebar. Turn off by setting it to false.

# Custom CSS and JS
customCSS = []
customJS = []

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.

titleCase = true # Capitalized title.

[codeBlock]
  maxLines = 30
  # lineNos = false # true/false represents that show/hide the line numbers by default.

[post]
  # excerpt = "description"
  # excerptMaxLength = 120

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

[creativeCommons]
  by = true # Credit must be given to you, the creator.
  nc = false # Only noncommercial use of your work is permitted.
  nd = false # No derivatives or adaptations of your work are permitted.
  sa = true # Adaptations must be shared under the same terms.

[utterances]
  repo = "panxiao81/new-blog" # Replace with your repository.
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  #theme = "github-dark" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

#[reward]
#  alipay = "images/reward/alipay.png"
#  wechat = "images/reward/wechat.png"

#[share]
  #addThis = "" # AddThis pubid.

[fontSize] # Comment or remove this settings to disable font size switcher.
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"

[pwa]
  [pwa.manifest]
    name = "" # Default to site title.
    short_name = "Pan"
    # display = "fullscreen" # Default to standalone.
    # description = "" # Default to site description.
    # theme_color = ""
    # background_color = ""

    # Icons
    # [[pwa.manifest.icons]]
    #   sizes = "96x96"
    #   src = "/images/icons/icon-96x96.png"
    # [[pwa.manifest.icons]]
    #   sizes = "144x144"
    #   src = "/images/icons/icon-144x144.png"

[contact]
  #endpoint = "https://getform.io/f/56041c81-9e03-4c24-b9c5-61238854d4cd" # Backend endpoint, remove this line if you're using Netlify.
  # file = true # Enable file upload
  # fileField = "image" # The name of file field.
