email = "pan-xiao@live.cn"
#facebook = "pan-xiao"
github = "panxiao81"
#gitlab = "yourgitlabusername"
linkedin = "in/潇-潘-4799b31a2"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
dockerhub = "panxiao81"
#bitbucket = "yourbitbucketworkspaceid"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
bilibili = "8695045"
